package com.banking.core.dto;

import jakarta.validation.constraints.NotBlank;

/**
 * Request to open a new customer account. A NUBAN is generated by the core.
 */
public record OpenAccountRequest(
        @NotBlank String firstName,
        @NotBlank String lastName,
        String email,
        String phone,
        String bvn,
        @NotBlank String accountType,
        String currency
) {
}
